<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continue</name>
   <tag></tag>
   <elementGuidId>47b0626f-1eb6-4173-8863-a06625a83ae5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.g-recaptcha.btn.btn-primary.mt-4.w-100</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='login']/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c22896e5-6815-448b-8533-d50a2697ac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>g-recaptcha btn btn-primary mt-4 w-100</value>
      <webElementGuid>b6a4c273-78c2-46d9-8ac5-8dac3d96c1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>10b9987b-bc8c-4851-bf92-b0abaf3d0e31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-callback</name>
      <type>Main</type>
      <value>onSubmitlogin</value>
      <webElementGuid>fc25f8aa-37cb-486a-ae9c-533bb401846b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-sitekey</name>
      <type>Main</type>
      <value>6Leg-zIbAAAAAJ3RDyp9ZW5JCjU1GkRWD9x4mzxW</value>
      <webElementGuid>23241fa9-3558-4180-9764-58cb7d94a1f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>3b3c2502-2164-4507-a3b5-e2af9cfd78ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)/button[@class=&quot;g-recaptcha btn btn-primary mt-4 w-100&quot;]</value>
      <webElementGuid>1fe2f24b-5227-45f9-85f3-f7696c3e40a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login']/button</value>
      <webElementGuid>3aaa39b6-ef0b-4a2d-b54d-9e1c2fbd1c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::button[1]</value>
      <webElementGuid>ef988a36-2649-4ca7-a29c-21de12064a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome Back!'])[2]/following::button[1]</value>
      <webElementGuid>ad2331b5-e9c0-4e92-bec0-b32d14942174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OR'])[1]/preceding::button[1]</value>
      <webElementGuid>1e409a5a-079d-4b88-beba-0b96a05b54ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>157066c3-c88c-45d6-b92d-361afabca492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Continue' or . = 'Continue')]</value>
      <webElementGuid>01004e75-6753-49d4-8cdd-dbd4ecc89db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
