<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Coastal Ecology</name>
   <tag></tag>
   <elementGuidId>59a2cd81-e4e4-482c-b3e7-158bf880492f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sc-c0ibFeUeng']/div[2]/div/a/h5/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.card-title-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ed69db86-d7af-4522-992f-e19bdc01d864</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-title-text</value>
      <webElementGuid>863c1b35-bde4-434a-868f-7195237a55a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Coastal Ecology</value>
      <webElementGuid>d1767725-2eac-4a64-b500-0b58b8b467ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;grid-items&quot;)/div[@class=&quot;col-12 col-sm-6 col-xl-3&quot;]/div[@id=&quot;sc-c0ibFeUeng&quot;]/div[@class=&quot;cursor-pointer card-body d-flex justify-content-between align-items-center&quot;]/div[@class=&quot;overflow-hidden w-100&quot;]/a[@class=&quot;card-link&quot;]/h5[@class=&quot;card-title d-inline-flex justify-content-start w-100&quot;]/div[@class=&quot;card-title-text&quot;]</value>
      <webElementGuid>5598b747-e6ad-4140-9273-a4bf75ac4e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sc-c0ibFeUeng']/div[2]/div/a/h5/div</value>
      <webElementGuid>9f27ae2b-2a44-43fc-9423-cc46727762d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Details'])[1]/following::div[3]</value>
      <webElementGuid>d8540506-4c74-431a-a638-f70742d6e3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Coastal Ecology']/parent::*</value>
      <webElementGuid>b5063b97-da31-4f76-94cf-02bb575f66fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h5/div</value>
      <webElementGuid>f81f3cf5-b725-4d97-b169-8cbab4d16dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Coastal Ecology' or . = 'Coastal Ecology')]</value>
      <webElementGuid>26d4f0d3-1b1e-40f6-841a-d9a6aa3420e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
