<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tina Taylor_profile-image-md</name>
   <tag></tag>
   <elementGuidId>5f3fc5bd-9036-45d4-910a-8ca2afce72d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.profile-image-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdownMenuLink']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ebbfb0bd-9a5c-48c6-a7ab-3adccc30600c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-image-md</value>
      <webElementGuid>3c203d45-caf2-4927-8cc6-f62648ab8754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg</value>
      <webElementGuid>9a2d0094-c0b7-4284-a7bd-43f2965e34ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>ad14adc4-6385-4136-a015-2decdc9acfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>c1c49dbf-ce0d-455b-924c-a4dc309e9248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdownMenuLink&quot;)/div[@class=&quot;profile-image-md&quot;]/img[@class=&quot;profile-image-md&quot;]</value>
      <webElementGuid>b44df44e-d31f-4f67-b815-f476b818fd4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdownMenuLink']/div/img</value>
      <webElementGuid>942d5f8f-8197-44e1-8fe3-d74f26ce838b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg')]</value>
      <webElementGuid>6402313c-4583-4d8f-9202-79171d8304a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/img</value>
      <webElementGuid>ffc23f61-c6f2-4053-a753-e212aea0b2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg']</value>
      <webElementGuid>49ada4cf-20d1-485b-b263-95db5ada1262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
