<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Tina Taylor_profile-image-md</name>
   <tag></tag>
   <elementGuidId>5f3fc5bd-9036-45d4-910a-8ca2afce72d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.profile-image-md</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdownMenuLink']/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1a3aa6ab-cc33-4051-94e3-14175d342a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-image-md</value>
      <webElementGuid>0dbb15d8-37b6-4200-a37b-4e82f894f36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg</value>
      <webElementGuid>5101bfc5-32a6-4ff7-83e5-b4ed80c18e02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>899dbbd2-96e9-442a-9c6e-08805f26438d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>70c3fbff-2f84-45f6-a785-f5eefed02a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdownMenuLink&quot;)/div[@class=&quot;profile-image-md&quot;]/img[@class=&quot;profile-image-md&quot;]</value>
      <webElementGuid>9052fd6d-3220-4fcb-a853-60951ba10f9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdownMenuLink']/div/img</value>
      <webElementGuid>12f739ee-a7e3-4a44-b99d-f9a6bd5b5720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg')]</value>
      <webElementGuid>ddc314f8-90c3-4f49-8999-20ac07077c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/div/img</value>
      <webElementGuid>98bd82d5-8c1a-4efc-80dc-ed18283ed96d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d1ka0itfguscri.cloudfront.net/user_profiles/profile_eaf4e830e389bb3214b621d9973ff32a.jpeg']</value>
      <webElementGuid>3eb499db-d804-4b3b-b982-02ddb20976d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
